<a href="https://colab.research.google.com/github/muzamiliqbalganaie/machine-learning-model-/blob/main/DAy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Get input from the user
num1 = float(input("Enter the first number: "))
num2 = float(input("Enter the secound number: "))

#perform the addition
sum_result = num1 + num2

#Display the result
print("The sum of {} and {} is: {}".format(num1,num2, sum_result))

Enter the first number: 1
Enter the secound number: 2
The sum of 1.0 and 2.0 is: 3.0


#Numpy-> Maths in Python
#Pandas-> (panel[multidimensional structures datas] datas)Read edit the data
#Matplotlib-> viz of the data
#Seaborn-> Top of matplotlib ,all graphics things
#sklearn-> used for running Machine learning algorithms

#3rd party lib/packages/modules
1. Data Collection
2. Data Cleaning and Pre processing
3. Expploration Data analysis(EDA)
4. Feature Engineering
5. Model Bulding and Training
6. Evaluation and validation
7. Iterative imporvement


jupiter is local app using local ram to run.

In [ ]:
! pip install numpy


In [ ]:
import numpy as np

In [ ]:
alist = [1,2,3,4,5]

alist*2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [ ]:
#base python

blist=[]
for a in alist:
  blist.append(a*2)
blist

[2, 4, 6, 8, 10]

In [ ]:
a_arr = np.array(alist)

In [ ]:
a_arr*2

array([ 2,  4,  6,  8, 10])

In [ ]:
import random

In [ ]:
np.random.randint(low=1000000, high=99999999, size=(2))

array([79580574, 65289137])

In [ ]:
d_arr = np.random.randint(low=100, high=999,size=(6,6))

In [ ]:
d_arr


array([[360, 254, 556, 396, 323, 594],
       [760, 699, 955, 743, 614, 862],
       [635, 643, 174, 304, 145, 103],
       [848, 885, 689, 858, 171, 309],
       [444, 765, 587, 727, 532, 687],
       [524, 745, 245, 360, 283, 365]])

In [ ]:
d_arr.max()

955

In [ ]:
d_arr.min()

103

In [ ]:
d_arr.std()
#standard devation

237.9963948269328

In [ ]:
d_arr

array([[360, 254, 556, 396, 323, 594],
       [760, 699, 955, 743, 614, 862],
       [635, 643, 174, 304, 145, 103],
       [848, 885, 689, 858, 171, 309],
       [444, 765, 587, 727, 532, 687],
       [524, 745, 245, 360, 283, 365]])

In [ ]:
d_arr[2:3,3:5]

array([[304, 145]])

In [ ]:
d_arr[2,1]

643

In [ ]:
d_arr[4:5,3:6]

array([[727, 532, 687]])

In [ ]:
# Slicing
# Syntax => arr_name[row_start_num:row_end_num,col_start_num:col_end_num]